name: Vinh Le
title: A Website For A Guy Who Likes AI and Games
description: MIT Graduate, Bachelors and Masters in Computation and Cognition
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
  - coder
  - gamer
  - software engineer
  - data scientist
  - mit
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: youremail@test.com
# See: https://disqus.com/
disqus_username:
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
